import React from 'react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { ScrollArea } from '@/components/ui/scroll-area';
const TermsOfUseDialog = () => {
  const [open, setOpen] = React.useState(false);
  return <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <button className="text-sm text-legal-primary hover:text-legal-accent" onClick={() => setOpen(true)}>
          Terms of Use
        </button>
      </DialogTrigger>
      <DialogContent className="max-w-3xl max-h-[90vh]">
        <DialogHeader>
          <DialogTitle className="text-2xl font-bold text-legal-primary">SpeakLegal – Terms of Use</DialogTitle>
          <DialogDescription className="text-sm text-foreground/70 dark:text-foreground">
            Effective Date: May 5, 2025
          </DialogDescription>
        </DialogHeader>
        
        <ScrollArea className="max-h-[70vh] pr-4">
          <div className="space-y-4 py-4">
            <p className="text-foreground dark:text-foreground">
              Welcome to SpeakLegal! These Terms of Use govern your access to and use of the SpeakLegal mobile application and services. By using SpeakLegal, you agree to comply with and be bound by these Terms. If you do not agree, please discontinue use of the App.
            </p>
            
            <div>
              <h3 className="font-bold text-legal-primary">1. Use of the App</h3>
              <p className="text-foreground dark:text-foreground mt-2">
                SpeakLegal is a tool designed to simplify and summarize legal documents using artificial intelligence. You may use the App only for lawful purposes and in accordance with these Terms. You agree not to:
              </p>
              <ul className="list-disc ml-6 mt-2 space-y-2">
                <li className="text-foreground dark:text-foreground">Use the App to generate, upload, or share fraudulent, illegal, or harmful content.</li>
                <li className="text-foreground dark:text-foreground">Reverse-engineer, modify, or redistribute the App or any part of it.</li>
                <li className="text-foreground dark:text-foreground">Attempt to access or disrupt the App's underlying infrastructure.</li>
              </ul>
            </div>
            
            <div>
              <h3 className="font-bold text-legal-primary">2. No Legal Advice</h3>
              <p className="text-foreground dark:text-foreground mt-2">
                SpeakLegal is not a law firm and does not offer legal advice. The content generated by the App, including summaries, questions, and suggestions, is for informational purposes only. You should not rely on the App as a substitute for professional legal counsel. Always seek advice from a licensed attorney for formal legal matters.
              </p>
            </div>
            
            <div>
              <h3 className="font-bold text-legal-primary">3. AI-Generated Content</h3>
              <p className="text-foreground dark:text-foreground mt-2">
                The App uses artificial intelligence to generate simplified summaries of legal documents. While we aim for accuracy, the AI may not fully capture the complexity or nuances of a document. We make no guarantees regarding the completeness or legal validity of any AI-generated content. SpeakLegal and its developers are not responsible for any consequences that arise from using the App's content.
              </p>
            </div>
            
            <div>
              <h3 className="font-bold text-legal-primary">4. User-Uploaded Content</h3>
              <p className="text-foreground dark:text-foreground mt-2">
                You retain ownership of all documents uploaded to the App. By using SpeakLegal, you grant us a non-exclusive, temporary license to process and analyze the content solely for the purpose of generating summaries and suggestions. We do not sell, share, or store your documents for any other purpose.
              </p>
            </div>
            
            <div>
              <h3 className="font-bold text-legal-primary">5. Limitation of Liability</h3>
              <p className="text-foreground dark:text-foreground mt-2">
                SpeakLegal, its developers, and affiliates are not liable for any damages resulting from your use of the App, including but not limited to direct, indirect, incidental, or consequential damages. You use the App at your own risk, and we disclaim all warranties related to the accuracy and reliability of the App.
              </p>
            </div>
            
            <div>
              <h3 className="font-bold text-legal-primary">6. Termination</h3>
              <p className="text-foreground dark:text-foreground mt-2">
                We reserve the right to suspend or terminate your access to the App at any time, with or without notice, if we suspect misuse or violation of these Terms.
              </p>
            </div>
            
            <div>
              
              
            </div>
            
            <div>
              <h3 className="font-bold text-legal-primary">7. Contact Us</h3>
              <p className="text-foreground dark:text-foreground mt-2">
                For any questions or concerns about these Terms, please contact us at:
                <br />
                <span className="font-medium">sheditzofficial918@gmail.com | adilalalim2008@gmail.com</span>
              </p>
            </div>
            
            <p className="text-foreground dark:text-foreground italic">
              By using SpeakLegal, you confirm that you have read, understood, and agree to these Terms of Use.
            </p>
          </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>;
};
export default TermsOfUseDialog;
